JCC = javac

JFLAGS = -g

default: Pqueue.class SpanningTree.class

Pqueue.class : Pqueue.java
	$(JCC) $(JFLAGS) Pqueue.java

SpanningTree.class : SpanningTree.java
	$(JCC) $(JFLAGS) SpanningTree.java

clean: 
	$(RM) *.class
