
JCC = javac

JFLAGS = -g

default: AISD22.class InsertionSort.class QuickSort.class MergeSort.class

	
AISD22.class: AISD22.java
	$(JCC) $(JFLAGS)  AISD22.java
	
InsertionSort.class: InsertionSort.java
	$(JCC) $(JFLAGS) InsertionSort.java

QuickSort.class: QuickSort.java
	$(JCC) $(JFLAGS) QuickSort.java

MergeSort.class: MergeSort.java
	$(JCC) $(JFLAGS) MergeSort.java
	
clean: 
	$(RM) *.class	

