JCC = javac

JFLAGS = 

all: program1 program2 program3

program1:
	cd zad1; $(JCC) $(JFLAGS) Zad1.java

program2: 
	cd zad2; $(JCC) $(JFLAGS) Zad2.java

program3:
	cd zad3; $(JCC) $(JFLAGS) Zad3.java 
	
clean: 
	$(RM) *.class
