JCC = javac

JFLAGS = -g

default: zad4.class zad3.class PriorityQueue.class QueueElement.class PriorityQueue2.class QueueElement2.class DisjontSets.class

zad4.class : zad4.java
	$(JCC) $(JFLAGS) zad4.java
	
zad3.class : zad3.java
	$(JCC) $(JFLAGS) Main.java
	
PriorityQueue.class: PriorityQueue.java
	$(JCC) $(JFLAGS) PriorityQueue.java
	
QueueElement.class: QueueElement.java
	$(JCC) $(JFLAGS) QueueElement.java
	
PriorityQueue2.class: PriorityQueue2.java
	$(JCC) $(JFLAGS) PriorityQueue2.java
	
QueueElement2.class: QueueElement2.java
	$(JCC) $(JFLAGS) QueueElement2.java
	
DisjontSets.class: DisjontSets.java
	$(JCC) $(JFLAGS) DisjontSets.java
	
clean:
	$(RM) *.class
	
