JCC = javac

JFLAGS = -g

default: Pqueue.class SpanningTree.class Traverse.class

Pqueue.class : Pqueue.java
	$(JCC) $(JFLAGS) Pqueue.java

SpanningTree.class : SpanningTree.java
	$(JCC) $(JFLAGS) SpanningTree.java

Traverse.class : Traverse.java
	$(JCC) $(JFLAGS) Traverse.java

clean: 
	$(RM) *.class
